import { StyleSheet } from "react-native";
import { ms } from "../../utlils/deviceConfig";
import { colors } from "../../utlils/colors";

export const styles = StyleSheet.create({
     scrollContainer: {
       flexGrow: 1,
       backgroundColor: colors.background,
       paddingTop: ms(24),
       alignItems: 'center',
     },
     container: {
       flex: 1,
       backgroundColor: colors.background,
       alignItems: 'center',
       paddingTop: ms(24),
     },
     cardWrapper: {
       backgroundColor: colors.quinary,
       borderRadius: 14,
       borderWidth: 2,
       borderColor: colors.borderYellowColor,
       padding: ms(18),
       width: '92%',
       shadowColor: colors.black,
       shadowOpacity: 0.08,
       shadowRadius: 8,
       shadowOffset: { width: 0, height: 2 },
       elevation: 2,
       marginBottom: ms(24),
     },
     tripTypeRow: {
       flexDirection: 'row',
       justifyContent: 'space-between',
       marginBottom: ms(18),
     },
     tripTypeOption: {
       flexDirection: 'row',
       alignItems: 'center',
     },
     radioCircle: {
       height: ms(20),
       width: ms(20),
       borderRadius: ms(10),
       borderWidth: 2,
       borderColor: colors.primary,
       alignItems: 'center',
       justifyContent: 'center',
       marginRight: ms(6),
     },
     radioDot: {
       height: ms(10),
       width: ms(10),
       borderRadius: ms(5),
       backgroundColor: colors.primary,
     },
     tripTypeLabel: {
       fontSize: ms(16),
       color: colors.textColor,
       marginRight: ms(16),
     },
     row: {
       flexDirection: 'row',
       alignItems: 'center',
       paddingVertical: ms(10),
       borderBottomWidth: 1,
       borderBottomColor: colors.quaternary,
     },
     icon: {
       fontSize: ms(22),
       marginRight: ms(10),
     },
     swapIcon: {
       fontSize: ms(18)     ,
       marginLeft: 'auto',
       color: colors.primary,
     },
     boldText: {
       fontWeight: 'bold',
       fontSize: ms(16),
     },
     normalText: {
       fontSize: ms(16),
     },
     searchButton: {
       backgroundColor: colors.primary,
       borderRadius: 8,
       marginTop: ms(18),
       paddingVertical: ms(14),
       alignItems: 'center',
       zIndex:0
     },
     searchButtonText: {
       color: colors.quinary,
       fontWeight: 'bold',
       fontSize: ms(18),
     },
     directRow: {
       flexDirection: 'row',
       alignItems: 'center',
       marginTop: ms(8),
       width: '92%',
       justifyContent: 'space-between',
     },
     directText: {
       fontSize: ms(16),
       color: colors.textColor,
     },
     modalOverlay: {
       flex: 1,
       backgroundColor: colors.black,
   
       justifyContent: 'center',
       alignItems: 'center',
     },
     modalContent: {
       backgroundColor: colors.quinary,
       borderRadius: 12,
       padding: ms(16),
       width: '95%',
       alignItems: 'center',
     },
     closeButton: {
       marginTop: ms(16),
       paddingVertical: ms(10),
       paddingHorizontal: ms(24),
       backgroundColor: colors.primary,
       borderRadius: 8,
     },
     closeButtonText: {
       color: colors.quinary,
       fontWeight: 'bold',
       fontSize: ms(16),
     },
     multiCitySegment: {
       borderBottomWidth: 2,
       borderBottomColor: colors.borderYellowColor,
       marginBottom: 0,
       paddingBottom: 0,
     },
     addFlightButton: {
       alignItems: 'center',
       paddingVertical: ms(16),
     },
     addFlightText: {
       color: colors.primary,
       fontSize: ms(18),
       fontWeight: '500',
     },
     addRemoveRow: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'space-between',
       width: '100%',
     },
     removeFlightButton: {
              paddingVertical: ms(12),
       paddingHorizontal: ms(18),
       marginLeft: ms(8),
       backgroundColor: colors.quinary,
       borderRadius: 20,
       borderWidth: 1,
       borderColor: colors.quaternary,
       alignItems: 'center',
       justifyContent: 'center',
     },
     removeFlightButtonDisabled: {
       opacity: 0.4,
     },
     removeFlightText: {
       color: colors.red,
       fontSize: ms(24),
       fontWeight: 'bold',
     },
     removeFlightTextDisabled: {
       color: colors.secondary,
     },
     input: {
       borderWidth: 1,
       borderColor: colors.senary,
       borderRadius: 8,
       paddingHorizontal: ms(12),
       paddingVertical: ms(10),
       fontSize: ms(16),
       backgroundColor: colors.tertiary,
       marginBottom: 2,
     },
     dropdown: {
       position: 'absolute',
       top: ms(44),
       left: 0,
       right: 0,
       backgroundColor: colors.quinary,
       borderWidth: 1,
       borderColor: colors.senary,
       borderRadius: 8,
       zIndex: 10,
       shadowColor: colors.black,
       shadowOpacity: 0.08,
       shadowRadius: 8,
       shadowOffset: { width: 0, height: 2 },
       elevation: 3,
     },
     dropdownItem: {
       paddingVertical: ms(10),
       paddingHorizontal: ms(16),
       borderBottomWidth: 1,
       borderBottomColor: colors.quaternary,
     },
     dropdownItemText: {
       fontSize: ms(16),
       color: colors.textColor,
     },
     passengerClassRow: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'space-between',
       marginVertical: ms(8),
       width: '100%',
     },
     passengerSelector: {
       flexDirection: 'row',
       alignItems: 'center',
       backgroundColor: colors.tertiary,
       borderRadius: 8,
       borderWidth: 1,
       borderColor: colors.senary,
       paddingHorizontal: ms(8),
       paddingVertical: ms(4),
     },
     passengerButton: {
       paddingHorizontal: ms(12),
       paddingVertical: ms(4),
       borderRadius: 6,
       backgroundColor: colors.quinary,
       borderWidth: 1,
       borderColor: colors.quaternary,
       marginHorizontal: ms(2),
     },
     passengerButtonDisabled: {
       opacity: 0.4,
     },
     passengerButtonText: {
       fontSize: ms(20),
          color: colors.primary,
       fontWeight: 'bold',
     },
     passengerButtonTextDisabled: {
       color: colors.secondary,
     },
     passengerCountText: {
       fontSize: ms(16),
       marginHorizontal: ms(8),
       color: colors.textColor,
     },
     classSelectorWrapper: {
       marginLeft: ms(12),
       position: 'relative',  
       flex: 1,
     },
     classSelector: {
       flexDirection: 'row',
       alignItems: 'center',
       backgroundColor: colors.tertiary,
       borderRadius: 8,
       borderWidth: 1,
       borderColor: colors.senary,
       paddingHorizontal: ms(14),
       paddingVertical: ms(10),
       justifyContent: 'space-between',
     },
     classSelectorText: {
       fontSize: ms(16),
       color: colors.textColor,
     },
     classSelectorArrow: {
       fontSize: 14,
       color: colors.secondaryTextColor,
       marginLeft: 6,
     },
     classDropdown: {
       position: 'absolute',
       top: ms(48),
       left: 0,
       right: 0,
       backgroundColor: colors.quinary,
       borderWidth: 1,
       borderColor: colors.senary,
       borderRadius: 8,
       zIndex: 20,
       shadowColor: colors.black,
       shadowOpacity: 0.08,
       shadowRadius: 8,
       shadowOffset: { width: 0, height: 2 },
       elevation: 3,
     },
     classDropdownItem: {
       paddingVertical: ms(12),
       paddingHorizontal: ms(18),
       borderBottomWidth: 1,
       borderBottomColor: colors.quaternary,
     },
     classDropdownItemText: {
       fontSize: ms(16),
       color: colors.textColor,
     },
   });